[package]
name = "julix"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bitflags = "2.4"
crossterm = "0.27"
portable-pty = "0.8"
ratatui = "0.26"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
toml = "0.8"
vte = "0.13"

